import codeToImageConverter from "../../images/detail-page-images/codeToImageConverter.svg";
import BrowserExtensionBanner from "../../components/BrowserExtensionBanner";
import BuyMeACoffee from "../../components/BuyMeACoffee";
import CodeToImage from "../../components/CodeToImage";
import CommentsSection from "../../components/CommentsSection";
import SimilarTools from "../../components/SimilarTools";
import ToolsDetailPageHeader from "../../components/ToolsDetailPageHeader";

const CodeToImageConverter = () => {
    return (
        <div className="overflow-x-hidden">
            <ToolsDetailPageHeader title="Code to Image Converter" icon={codeToImageConverter} />

            <div className="w-full bg-gray-50 min-h-screen pt-4 pb-10 px-3 sm:px-4">

                <CodeToImage />

                {/* Components */}
                <div className="flex flex-col space-y-0">
                    <CommentsSection toolId="code-to-image-converter" />
                    <BuyMeACoffee />
                    <SimilarTools />
                    <BrowserExtensionBanner />
                    <div className="max-w-5xl mx-auto py-4 px-0">
                        <div className="bg-white rounded-2xl shadow-sm p-6 md:p-10 border border-gray-100 font-manrope">

                            {/* Section 1: Header & Intro */}
                            <h2 className="text-xl md:text-2xl font-bold text-gray-900 mb-6 font-space-grotesk">
                                What is Online Code to Image Converter?
                            </h2>

                            <div className="space-y-4 text-gray-700 leading-relaxed text-md md:text-base font-semibold">
                                <p>
                                    Code to Image Converter is a <span className="font-bold text-gray-900 border-b-2 border-[#b9b8ff]">free online tool for generating code images</span> and works as <span className="font-bold text-gray-900 border-b-2 border-[#b9b8ff]">code screenshot generator</span>. A programming language is a set of rules that used to communicate with computers and machines. They can be defined as computer languages, and they are responsible for generating algorithms that machines can understand. They are used for creating software, applications, games, operating systems, and many other things.
                                </p>
                                <p>
                                    In daily life of a software developer or engineer, it is very common to share his or her <span className="font-bold text-gray-900 border-b-2 border-[#b9b8ff]">code snippet online</span> with his colleagues, friends or even followers on social media like Twitter, LinkedIn and so on. It doesn't matter if you are a frontend, backend, or mobile developer or even a full stack developer, you can use this tool to generate code images and share your knowledge with the community. If you are a Devops engineer, then you can share your config files like Dockerfile etc. When you paste your code into the editor and select the programming language of the related block, it will highlight it automatically and generate a screenshot of the code when you click on the download button.
                                </p>
                                <p>
                                    There are many languages available for you to choose from popular ones to the most obscure ones. If you are using JavaScript, TypeScript HTML, CSS, Java, Python, PHP, Kotlin, Swift, Dart, Ruby, Rust, C#, Go or other programming languages and want to share tips, tricks, and knowledge with the community, all these languages will be auto highlighted which makes them easy to read and fancy. There are many light and dark themes available for highlighting including the most popular ones such as Dracula, A11y, Android Studio, XCode, Atom One, Github, Google Code, Intellij, Monokai, Night Owl, Nord, StackOverflow, Visual Studio Code and many more. As an addition to language highlighting, you can also choose the background color or image, monospace font family, font size, image quality, shadow attributes, and many other options. Popular monospace font families can be set such as Roboto Mono, Space Mono, PT Mono or Source Code Pro.
                                </p>
                                <p>
                                    Here, you can see JavaScript code image generated by online code screenshot generator.
                                </p>
                            </div>

                            {/* Section 2: Image Placeholder */}
                            <div className="my-10 flex flex-col items-center">
                                <div className="border border-gray-200 p-2 bg-white shadow-sm max-w-3xl w-full">
                                    <img
                                        src="https://10015.io/assets/tools/pages/code-to-image-converter/code-to-image-converter.png"
                                        alt="Code to Image Converter"
                                        className="w-full h-auto"
                                    />
                                </div>
                                <p className="text-xs text-gray-400 mt-4 text-center italic">
                                    Code to Image Converter Screenshot
                                </p>
                            </div>

                            <div className="space-y-4 text-gray-700 leading-relaxed text-md md:text-base font-semibold">
                                <p>
                                    If you make a presentation, conference talk or lecture about your software profession or your work, you can use these screenshots in your PowerPoint or Keynote presentations so that your work will look more professional and attractive with these snapshots. Carbon is a well-known application used for this purpose within developers and designers, but you have much more customization options with this tool.
                                </p>
                            </div>


                            {/* Section 3: How to Use */}
                            <h3 className="pt-4 text-xl font-bold text-gray-900 mb-6 font-space-grotesk">How to use Online Code to Image Converter?</h3>
                            <p className="text-gray-700 mb-4 text-lg font-semibold md:text-base">For converting your code to image, you can use the following steps:</p>
                            <ol className="space-y-4 text-md font-semibold md:text-base text-gray-700 list-decimal list-inside mb-10">
                                <li className="pl-2">Select the programming language, theme, and font family you want to use. When ready, paste your code in the editor. It will be automatically highlighted.</li>
                                <li className="pl-2">If you want to make further customization visually like font size, image quality, frame size or background color/image, you can tweak the settings.</li>
                                <li className='pl-2'>When you get the desired code image, you can export it. Use the option you need under "Export" button and either download the image or copy the image data into your clipboard.</li>
                                <li className="pl-2">You can turn on watermark option to support us if you like the tool. It is fully optional and off by default.</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default CodeToImageConverter;